
GET http://localhost:8080/health

POST http://localhost:8080/chat
Content-Type: application/json

{
  "message": "What is the capital of China?"
}


POST http://localhost:8080/chat
Content-Type: application/json

{
  "message": "Hello, my name is Will"
}


POST http://localhost:8080/chat
Content-Type: application/json

{
  "message": "What is my name?"
}


POST http://localhost:8080/chat/streaming
Content-Type: application/json

{
  "message": "Introduce China within 150 words"
}


POST http://localhost:8080/chat/streaming
Content-Type: application/json

{
  "message": "Analyze Spring-AI vs LangChain4j"
}
